export const Events = {
  REQUEST: 'REQUEST',
  LOGIN_OK: 'LOGIN_OK',
  LOGIN_FAIL: 'LOGIN_FAIL',
  NOTIFY_OK: 'NOTIFY_OK',
  NOTIFY_FAILED: 'NOTIFY_FAILED',
  ADMIN_USERS_ACCESS: 'ADMIN_USERS_ACCESS',
  TOKEN_ISSUED: 'TOKEN_ISSUED',
  JWT_SECRET_SOURCE: 'JWT_SECRET_SOURCE',
  SEED_DONE: 'SEED_DONE',
} as const;
